// Copyright 2022 noppikinatta
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

//     http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by genimg.go using 'go generate'. DO NOT EDIT.

package assets

const (
	ImgGameplayBg       Img = "g_bg.png"
	ImgGameplayRobot    Img = "g_robot.png"
	ImgPrologueBg       Img = "p_bg.png"
	ImgPrologueDoctor   Img = "p_doctor.png"
	ImgPrologueMsg1     Img = "p_msg1.png"
	ImgPrologueMsg2     Img = "p_msg2.png"
	ImgResultBg         Img = "r_bg.png"
	ImgResultEnemy      Img = "r_enemy.png"
	ImgResultExplosion  Img = "r_explosion.png"
	ImgResultFlame      Img = "r_flame.png"
	ImgResultMsgfailed  Img = "r_msgfailed.png"
	ImgResultMsgvictory Img = "r_msgvictory.png"
	ImgResultToreplay   Img = "r_toreplay.png"
	ImgTitleBg          Img = "t_bg.png"
	ImgTitleLogo        Img = "t_logo.png"
	ImgTitleRobot       Img = "t_robot.png"
)
